# https://github.com/lowlighter/metrics/blob/master/action.yml
# Plugins: https://github.com/lowlighter/metrics/tree/master/source/plugins

name: Generate Metrics
on:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/metrics.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: KJHJason
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Singapore
          config_twemoji: yes

          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200

          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_ignored: HTML,CSS
          plugin_languages_details: bytes-size, percentage

          plugin_lines: yes

      - name: Generate Anilist metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/anilist-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: classic
          config_timezone: Asia/Singapore
          config_twemoji: yes

          plugin_anilist: yes
          plugin_anilist_user: Dratornic
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching

      - name: Generate Spotify metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/spotify-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: classic
          config_timezone: Asia/Singapore
          config_twemoji: yes

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_mode: recent
          plugin_music_limit: 2
